# Generated by Django 2.0.7 on 2018-07-23 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(help_text='Enter e-mail', max_length=100, unique=True, verbose_name='E-mail'),
        ),
    ]
