# Generated by Django 2.0.7 on 2018-07-29 13:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180725_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='pretext',
            field=models.TextField(default='', max_length=500, verbose_name='Pre-text'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='posts',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Author of post'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='text',
            field=models.TextField(verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
    ]
