# Generated by Django 2.0.7 on 2018-07-31 15:07

from django.db import migrations
import django_summernote.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20180729_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='pretext',
            field=django_summernote.fields.SummernoteTextField(max_length=500, verbose_name='Pre-text'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='text',
            field=django_summernote.fields.SummernoteTextField(verbose_name='Text'),
        ),
    ]
