# Generated by Django 2.0.7 on 2018-08-01 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20180731_2207'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedIP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(verbose_name='IP-adress')),
                ('attempts', models.IntegerField(default=0, verbose_name='Attempts')),
                ('is_blocked', models.BooleanField(default=False, verbose_name='Is blocked')),
            ],
        ),
    ]
