# Generated by Django 2.0.7 on 2018-08-01 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_blockedip'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blockedip',
            options={'verbose_name': 'Blocked IP', 'verbose_name_plural': "Blocked IP's"},
        ),
    ]
