# Generated by Django 2.0.7 on 2018-08-02 08:36

from django.db import migrations
import django_summernote.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20180801_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='pretext',
            field=django_summernote.fields.SummernoteTextField(verbose_name='Pre-text'),
        ),
    ]
